name: Docker build

on:
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: ['api', 'keycloak']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: 'recursive'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.component }}
          file: ./${{ matrix.component }}/Dockerfile
          push: false
          tags: usdotjpoode/jpo-conflictvisualizer-${{ matrix.component }}:${{ github.ref_name }}
