name: CI
on: 
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [develop, master, feature/gha]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build and run Sonar analysis for jpo-conflictvisualizer-api
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE/api
          cd jpo-conflictmonitor/jpo-conflictmonitor/
          mvn -e -X clean install
          cd $GITHUB_WORKSPACE/api/jpo-conflictvisualizer-api
          mvn -e -X clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=usdot-jpo-ode_jpo-conflictvisualizer -Dsonar.projectName=jpo-conflictvisualizer -Dsonar.organization=usdot-jpo-ode -Dsonar.host.url=https://sonarcloud.io -Dsonar.branch.name=$GITHUB_REF_NAME
