name: CI

on: 
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [develop, master, feature/gha]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive 

      - name: Set up JDK
        uses: actions/setup-java@v4 
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and Run Sonar Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE/api/jpo-conflictmonitor/jpo-geojsonconverter/jpo-ode
          mvn install -DskipTests
          cd ../jpo-geojsonconverter
          mvn install -DskipTests
          cd $GITHUB_WORKSPACE/api/jpo-conflictmonitor/test-message-sender
          mvn clean install -DskipTests
          cd ../jpo-conflictmonitor
          mvn clean install -DskipTests
          cd $GITHUB_WORKSPACE/api/jpo-conflictvisualizer-api
          mvn -e -X clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=usdot-jpo-ode_jpo-conflictvisualizer -Dsonar.projectName=jpo-conflictvisualizer -Dsonar.java.binaries=$GITHUB_WORKSPACE/api/jpo-conflictvisualizer-api/target/classes -Dsonar.coverage.jacoco.xmlReportPaths=$GITHUB_WORKSPACE/api/jpo-conflictvisualizer-api/target/site/jacoco/jacoco.xml -Dsonar.organization=usdot-jpo-ode -Dsonar.host.url=https://sonarcloud.io -Dsonar.branch.name=$GITHUB_REF_NAME
